# 注意事项：
# 1. 数据存储于`/usr/local/dataflux-func/`目录下，
#    部署前应当保证目录已经存在。
#    参考命令：
#       sudo mkdir -p /usr/local/dataflux-func/{data,data/extra-python-packages,mysql,redis}
#
# 2. 使用`docker stack`即进行部署。
#    参考命令（假设本配置文件名为"docker-stack.yaml"）：
#       sudo docker stack deploy dataflux-func -c docker-stack.yaml

version: '3.1'

services:
  # BOF MYSQL
  mysql:
    image: <MYSQL_IMAGE>
    networks:
      - datafluxfunc
    volumes:
      - "<INSTALL_DIR>/mysql:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=<RANDOM_PASSWORD>"
      - "MYSQL_DATABASE=dataflux_func"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  # EOF MYSQL

  # BOF REDIS
  redis:
    image: <REDIS_IMAGE>
    networks:
      - datafluxfunc
    volumes:
      - "<INSTALL_DIR>/redis:/data"
  # EOF REDIS

  server:
    image: <DATAFLUX_FUNC_IMAGE>
    volumes:
      - "<INSTALL_DIR>/data:/data"
    depends_on:
      - mysql
      - redis
    networks:
      - datafluxfunc
      - default
    ports:
      - "8088:8088"
    command: ./run-server.sh

  worker-0:
    image: <DATAFLUX_FUNC_IMAGE>
    volumes:
      - "<INSTALL_DIR>/data:/data"
    depends_on:
      - mysql
      - redis
    networks:
      - datafluxfunc
      - default
    command: ./run-worker-by-queue.sh 0

  worker-1-6:
    image: <DATAFLUX_FUNC_IMAGE>
    volumes:
      - "<INSTALL_DIR>/data:/data"
    depends_on:
      - mysql
      - redis
    networks:
      - datafluxfunc
      - default
    command: ./run-worker-by-queue.sh 1 2 3 4 5 6

  worker-7:
    image: <DATAFLUX_FUNC_IMAGE>
    volumes:
      - "<INSTALL_DIR>/data:/data"
    depends_on:
      - mysql
      - redis
    networks:
      - datafluxfunc
      - default
    command: ./run-worker-by-queue.sh 7

  worker-8-9:
    image: <DATAFLUX_FUNC_IMAGE>
    volumes:
      - "<INSTALL_DIR>/data:/data"
    depends_on:
      - mysql
      - redis
    networks:
      - datafluxfunc
      - default
    command: ./run-worker-by-queue.sh 8 9

  beat:
    image: <DATAFLUX_FUNC_IMAGE>
    volumes:
      - "<INSTALL_DIR>/data:/data"
    depends_on:
      - mysql
      - redis
    networks:
      - datafluxfunc
      - default
    command: ./run-beat.sh

  # BOF EMQX
  emqx:
    image: <EMQX_IMAGE>
    ports:
      - "1883:1883"
    environment:
      - "EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_auth_http"
      - "EMQX_AUTH__HTTP__AUTH_REQ=http://server:8088/api/v1/func/integration/auth-emqx"
      - "EMQX_AUTH__HTTP__AUTH_REQ__METHOD=post"
      - "EMQX_AUTH__HTTP__AUTH_REQ__PARAMS=clientid=%c,username=%u,password=%P"
      - "EMQX_ALLOW_ANONYMOUS=false"
      - "EMQX_MANAGEMENT__DEFAULT_APPLICATION__ID=dataflux_func"
      - "EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET=<RANDOM_PASSWORD>"
  # EOF EMQX

networks:
  default:
    external:
      name: bridge
  datafluxfunc:
    driver: overlay
