# 注意事项：
# 1. 数据存储于`/usr/local/dataflux-func/`目录下，
#    部署前应当保证目录已经存在。
#    参考命令：
#       sudo mkdir -p /usr/local/dataflux-func/{data,data/extra-python-packages,mysql,redis}
#
# 2. 使用`docker stack`即进行部署。
#    参考命令（假设本配置文件名为"docker-stack.yaml"）：
#       sudo docker stack deploy dataflux-func -c docker-stack.yaml

version: '3.1'

services:
  mysql:
    image: mysql:5.7.26
    networks:
      - datafluxfunc
    volumes:
      - "/usr/local/dataflux-func/mysql:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql_root_password"
      - "MYSQL_DATABASE=dataflux_func"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:5.0.7
    networks:
      - datafluxfunc
    volumes:
      - "/usr/local/dataflux-func/redis:/data"

  server:
    image: pubrepo.jiagouyun.com/dataflux-func/dataflux-func:latest
    volumes:
      - "/usr/local/dataflux-func/data:/data"
    depends_on:
      - mysql
      - redis
    networks:
      - datafluxfunc
      - default
    ports:
      - "8088:8088"
    command: ./run-server.sh

  worker:
    image: pubrepo.jiagouyun.com/dataflux-func/dataflux-func:latest
    volumes:
      - "/usr/local/dataflux-func/data:/data"
    depends_on:
      - mysql
      - redis
    networks:
      - datafluxfunc
      - default
    command: ./run-worker.sh

  beat:
    image: pubrepo.jiagouyun.com/dataflux-func/dataflux-func:latest
    volumes:
      - "/usr/local/dataflux-func/data:/data"
    depends_on:
      - mysql
      - redis
    networks:
      - datafluxfunc
      - default
    command: ./run-beat.sh

networks:
  default:
    external:
      name: bridge
  datafluxfunc:
    driver: overlay
